/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_gabrielgiron_12051024;

import java.awt.event.MouseEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Galex
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        POPUPMENU = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenuItem();
        Imprimir = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PTemperatura = new javax.swing.JSpinner();
        PTamaño = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        PAgua = new javax.swing.JCheckBox();
        RegistrarPlaneta = new javax.swing.JButton();
        RazaBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RNombre = new javax.swing.JTextField();
        RegistrarRaza = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        EName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EListaPlanetas = new javax.swing.JList<>();
        EEdad = new javax.swing.JSpinner();
        CAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ELista = new javax.swing.JList<>();
        EAmenaza = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        ERaza = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        EPlanetaF = new javax.swing.JComboBox<>();
        EGuardar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        CNombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CEdad = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        CRaza = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        CAtrapados = new javax.swing.JSpinner();
        CAmenaza = new javax.swing.JCheckBox();
        CGuardar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CNEdad = new javax.swing.JSpinner();
        CNName = new javax.swing.JTextField();
        CNRaza = new javax.swing.JComboBox<>();
        CNAmenaza = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        CNListaPlanetas = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        CNPlanetasC = new javax.swing.JList<>();
        CNGuardar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        AEdad = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        AAmenaza = new javax.swing.JCheckBox();
        ANombre = new javax.swing.JTextField();
        ARaza = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        AAbducidos = new javax.swing.JSpinner();
        AGuardar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListaAliens = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        Arbolito = new javax.swing.JTree();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        EditarPF = new javax.swing.JComboBox<>();
        EditarRaza = new javax.swing.JComboBox<>();
        EditarName = new javax.swing.JTextField();
        EditarEdad = new javax.swing.JSpinner();
        jScrollPane7 = new javax.swing.JScrollPane();
        EditarListaPlanetas = new javax.swing.JList<>();
        EditarAdd = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        EditarLista = new javax.swing.JList<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        EditarAmenaza = new javax.swing.JCheckBox();
        EditarBoton = new javax.swing.JButton();
        EditarHAtrapados = new javax.swing.JSpinner();
        EditarAAtrapados = new javax.swing.JSpinner();
        ComboPlanetas = new javax.swing.JComboBox<>();

        jLabel25.setText("jLabel25");

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        POPUPMENU.add(Eliminar);

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        POPUPMENU.add(Editar);

        Imprimir.setText("Imprimir");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });
        POPUPMENU.add(Imprimir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Razas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Planetas");

        jLabel3.setText("Nombre");

        jLabel4.setText("Temperatura");

        jLabel5.setText("Tamaño");

        PAgua.setText("Agua");

        RegistrarPlaneta.setText("Registrar Planeta");
        RegistrarPlaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarPlanetaActionPerformed(evt);
            }
        });

        RazaBox.setModel(new DefaultComboBoxModel());

        jLabel6.setText("Planeta Primordial");

        jLabel7.setText("Nombre");

        RegistrarRaza.setText("Registrar Raza");
        RegistrarRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarRazaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PAgua)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PName)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PTemperatura)
                    .addComponent(PTamaño)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrarPlaneta, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RazaBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RNombre)
                    .addComponent(RegistrarRaza, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addGap(104, 104, 104))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(498, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RazaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrarRaza))
                .addGap(18, 18, 18)
                .addComponent(PAgua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegistrarPlaneta)
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel2)
                    .addContainerGap(450, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Planetas y Razas", jPanel1);

        jLabel8.setText("Nombre");

        jLabel9.setText("Edad");

        EListaPlanetas.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(EListaPlanetas);

        CAdd.setText("Añadir a Su Lista");
        CAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAddActionPerformed(evt);
            }
        });

        ELista.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(ELista);

        EAmenaza.setText("Es Amenaza");

        jLabel10.setText("Raza");

        ERaza.setModel(new DefaultComboBoxModel());

        jLabel11.setText("Planeta Favorito");

        EPlanetaF.setModel(new DefaultComboBoxModel());

        EGuardar.setText("Guardar");
        EGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EName, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EEdad))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EAmenaza)
                            .addComponent(jLabel10)
                            .addComponent(ERaza, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(EPlanetaF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ERaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EPlanetaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EAmenaza)
                    .addComponent(EGuardar))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(CAdd))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Explorador", jPanel2);

        jLabel12.setText("Edad");

        jLabel13.setText("Nombre");

        jLabel14.setText("Raza");

        CRaza.setModel(new DefaultComboBoxModel());

        jLabel15.setText("Humanos Atrapados");

        CAmenaza.setText("Es Amenaza");

        CGuardar.setText("Guardar");
        CGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addComponent(CEdad))
                    .addComponent(CAmenaza))
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addComponent(CAtrapados, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CAtrapados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CAmenaza)
                    .addComponent(CGuardar))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cazador", jPanel3);

        jLabel16.setText("Raza");

        jLabel17.setText("Nombre");

        jLabel18.setText("Edad");

        CNRaza.setModel(new DefaultComboBoxModel());

        CNAmenaza.setText("Es Amenaza");

        jLabel19.setText("Planetas Conquistados");

        CNListaPlanetas.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(CNListaPlanetas);

        jButton1.setText("Añadir a Su Lista");

        CNPlanetasC.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(CNPlanetasC);

        CNGuardar.setText("Guardar");
        CNGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(CNAmenaza)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(CNEdad)
                            .addComponent(CNName)
                            .addComponent(CNRaza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(CNGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 37, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(CNName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CNEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel16))
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CNRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton1)))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNAmenaza)
                    .addComponent(CNGuardar))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conquistador", jPanel4);

        jLabel20.setText("Nombre");

        jLabel21.setText("Edad");

        jLabel22.setText("Animales Abducidos");

        AAmenaza.setText("Es Amenaza");

        ARaza.setModel(new DefaultComboBoxModel());

        jLabel23.setText("Raza");

        AGuardar.setText("Guardar");
        AGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ANombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(AEdad, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(AAmenaza))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ARaza, javax.swing.GroupLayout.Alignment.LEADING, 0, 145, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AAbducidos, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(AGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(126, 126, 126))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ARaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AAbducidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AAmenaza)
                    .addComponent(AGuardar))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Abduzcan", jPanel5);

        ListaAliens.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(ListaAliens);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        Arbolito.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        Arbolito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ArbolitoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ArbolitoMouseReleased(evt);
            }
        });
        jScrollPane6.setViewportView(Arbolito);

        jLabel24.setText("Edad");

        jLabel26.setText("Nombre");

        jLabel27.setText("Planeta Favorito");

        jLabel28.setText("Raza");

        EditarPF.setModel(new DefaultComboBoxModel());

        EditarRaza.setModel(new DefaultComboBoxModel());

        EditarListaPlanetas.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(EditarListaPlanetas);

        EditarAdd.setText("Añadir");

        EditarLista.setModel(new DefaultListModel());
        jScrollPane8.setViewportView(EditarLista);

        jLabel29.setText("Humanos Atrapados");

        jLabel30.setText("Animales Atrapados");

        EditarAmenaza.setText("Es Amenaza");

        EditarBoton.setText("Editar");
        EditarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBotonActionPerformed(evt);
            }
        });

        ComboPlanetas.setModel(new DefaultComboBoxModel());
        ComboPlanetas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboPlanetasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ComboPlanetas, 0, 136, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(EditarPF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EditarRaza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(EditarName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(EditarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(EditarAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditarHAtrapados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EditarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(EditarAmenaza)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditarAAtrapados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditarPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditarRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane7)
                                    .addComponent(jScrollPane8)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(EditarAdd)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(EditarHAtrapados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(EditarAAtrapados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(EditarAmenaza)
                        .addGap(18, 18, 18)
                        .addComponent(EditarBoton)
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(ComboPlanetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5)))
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Arbol", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarPlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarPlanetaActionPerformed
        // TODO add your handling code here:
        String Name = PName.getText();
        int Temperatura = (Integer) PTemperatura.getValue();
        int Tamaño = (Integer) PTamaño.getValue();
        boolean Agua = PAgua.isSelected();
        int cent = 0;
        for (int i = 0; i < M.getPlanetas().size(); i++) {
            if(M.getPlanetas().get(i).getNombre().equals(Name))
            {
                cent = 1;
                break;
            }
        }
        if(cent == 1)
        {
            JOptionPane.showMessageDialog(null, "Ese Planeta ya Existe");
        }
        else
        {
            Planetas P = new Planetas(Name,Temperatura,Tamaño,Agua);
            M.getPlanetas().add(P);
            JOptionPane.showMessageDialog(null, "Planeta Creado Exitosamente");
            UpdateFramePlanetas();
        }
        PName.setText("");
        PTemperatura.setValue(0);
        PTamaño.setValue(0);
    }//GEN-LAST:event_RegistrarPlanetaActionPerformed

    private void RegistrarRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarRazaActionPerformed
        // TODO add your handling code here:
        Planetas P = (Planetas) RazaBox.getSelectedItem();
        String Name = RNombre.getText();
        int cent = 0;
        for (int i = 0; i < M.getRazas().size(); i++) {
            if(M.getRazas().get(i).getNombre().equals(Name))
            {
                cent = 1;
                break;
            }
        }
        if(cent == 1)
        {
            JOptionPane.showMessageDialog(null, "Esa Raza ya Existe");
        }
        else
        {
            Raza R = new Raza(P,Name);
            M.getRazas().add(R);
            JOptionPane.showMessageDialog(null, "Raza Creado Exitosamente");
            UpdateFrameRazas();
        }
        RNombre.setText("");
    }//GEN-LAST:event_RegistrarRazaActionPerformed

    private void EGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EGuardarActionPerformed
        // TODO add your handling code here:
        String Name = EName.getText();
        int Edad = (Integer) EEdad.getValue();
        boolean Amenaza = EAmenaza.isSelected();
        Raza R = (Raza) ERaza.getSelectedItem();
        Planetas P = (Planetas) EPlanetaF.getSelectedItem();
        Explorador E = new Explorador(P,Name,Edad,Amenaza,R);
        DefaultListModel m = (DefaultListModel) ELista.getModel();
        for (int i = 0; i < m.getSize(); i++) {
            E.getPlanetasExplorados().add((Planetas) m.getElementAt(i));
        }
        R.getPlanetaPrimordial().getAlien().add(E);
        JOptionPane.showMessageDialog(null, "Explorador Agregado Exitosamente");
        m.removeAllElements();
        EName.setText("");
        EEdad.setValue(0);
        ELista.setModel(m);
    }//GEN-LAST:event_EGuardarActionPerformed

    private void CAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAddActionPerformed
        // TODO add your handling code here:
        DefaultListModel L = (DefaultListModel) ELista.getModel();
        DefaultComboBoxModel R = (DefaultComboBoxModel) EPlanetaF.getModel();
        int a = EListaPlanetas.getSelectedIndex();
        Planetas P = M.getPlanetas().get(a);
        DefaultListModel m = (DefaultListModel) ELista.getModel();
        int cent = 0;
        for (int i = 0; i < m.getSize(); i++) {
            if(((Planetas)m.getElementAt(i)).getNombre().equals(P.getNombre()))
            {
                cent = 1;
                break;
            }
        }
        if(cent == 1)
        {
            JOptionPane.showMessageDialog(null, "Ese Planeta ya fue agregado a los planetas Explorados");
        }
        else
        {
            L.addElement(P);
            ELista.setModel(L);
            R.addElement(P);
            EPlanetaF.setModel(R);
        }
    }//GEN-LAST:event_CAddActionPerformed

    private void CGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGuardarActionPerformed
        // TODO add your handling code here:
        String Name = CNombre.getText();
        int Edad = (Integer) CEdad.getValue();
        boolean Amenaza = CAmenaza.isSelected();
        Raza R = (Raza) CRaza.getSelectedItem();
        int HumanosAtrapados = (Integer) CAtrapados.getValue();
        Cazador C = new Cazador(HumanosAtrapados,Name,Edad,Amenaza,R);
        R.getPlanetaPrimordial().getAlien().add(C);
        JOptionPane.showMessageDialog(null, "Cazador Agregado Exitosamente");
        CNombre.setText("");
        CEdad.setValue(0);
        CAtrapados.setValue(0);
    }//GEN-LAST:event_CGuardarActionPerformed

    private void AGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGuardarActionPerformed
        // TODO add your handling code here:
        String Name = ANombre.getText();
        int Edad = (Integer) AEdad.getValue();
        boolean Amenaza = AAmenaza.isSelected();
        Raza R = (Raza) ARaza.getSelectedItem();
        int AnimalesAtrapados = (Integer) AAbducidos.getValue();
        Abduzcan A = new Abduzcan(AnimalesAtrapados,Name,Edad,Amenaza,R);
        R.getPlanetaPrimordial().getAlien().add(A);
        JOptionPane.showMessageDialog(null, "Abduzcan Agregado Exitosamente");
        ANombre.setText("");
        AEdad.setValue(0);
        AAbducidos.setValue(0);
    }//GEN-LAST:event_AGuardarActionPerformed

    private void CNGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNGuardarActionPerformed
        // TODO add your handling code here:
        String Name = EName.getText();
        int Edad = (Integer) EEdad.getValue();
        boolean Amenaza = EAmenaza.isSelected();
        Raza R = (Raza) ERaza.getSelectedItem();
        Conquistador C = new Conquistador(Name,Edad,Amenaza,R);
        DefaultListModel m = (DefaultListModel) CNListaPlanetas.getModel();
        for (int i = 0; i < m.getSize(); i++) {
            C.getPlanetasConquistados().add((Planetas) m.getElementAt(i));
        }
        R.getPlanetaPrimordial().getAlien().add(C);
        JOptionPane.showMessageDialog(null, "Conquistador Agregado Exitosamente");
        m.removeAllElements();
        EName.setText("");
        EEdad.setValue(0);
        CNListaPlanetas.setModel(m);
    }//GEN-LAST:event_CNGuardarActionPerformed

    private void ComboPlanetasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboPlanetasItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == 2)
        {
            Planetas P = (Planetas)ComboPlanetas.getSelectedItem();
            DefaultListModel L = (DefaultListModel) ListaAliens.getModel();
            L.removeAllElements();
            for(int i = 0; i < P.getAlien().size(); i++)
            {
                L.addElement(P.getAlien().get(i));
            }
            ListaAliens.setModel(L);
        }
    }//GEN-LAST:event_ComboPlanetasItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(ListaAliens.getSelectedIndex() >= 0)
        {
            DefaultTreeModel ModeloArbol = (DefaultTreeModel) Arbolito.getModel();
            DefaultMutableTreeNode Raiz = (DefaultMutableTreeNode) ModeloArbol.getRoot();
            DefaultListModel Lista = (DefaultListModel) ListaAliens.getModel();
            Aliens A = (Aliens) Lista.get(ListaAliens.getSelectedIndex());
            String Nombre = A.getNombre();
            int Edad = A.getEdad();
            boolean Amenaza = A.isAmenaza();
            Raza R = A.getRaza();
            int cent = -1;
            for (int i = 0; i < Raiz.getChildCount(); i++) {
                if(Raiz.getChildAt(i).toString().equals(R.getPlanetaPrimordial().getNombre()))
                {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Aliens(Nombre,Edad,Amenaza,R));
                    ((DefaultMutableTreeNode) Raiz.getChildAt(i)).add(p);
                    cent = 1;
                }
            }
            
            if(cent == -1)
            {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(R.getPlanetaPrimordial().getNombre());
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Aliens(Nombre,Edad,Amenaza,R));
                n.add(p);
                Raiz.add(n);
            }
            ModeloArbol.reload();
        }
        else {
            JOptionPane.showMessageDialog(this,
                    "No hay persona seleccionada");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void PopUp(MouseEvent e)
    {
        Object v1 = Arbolito.getSelectionPath().getLastPathComponent();
        NodoSeleccionado = (DefaultMutableTreeNode) v1;
        if(NodoSeleccionado.getUserObject() instanceof Aliens)
        {
            AlienSeleccionado = (Aliens) NodoSeleccionado.getUserObject();
            POPUPMENU.show(this, e.getX()+150, e.getY()+150);
        }
    }
    
    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) Arbolito.getModel();
        m.removeNodeFromParent(NodoSeleccionado);
        m.reload();
    }//GEN-LAST:event_EliminarActionPerformed

    private void ArbolitoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArbolitoMousePressed
        // TODO add your handling code here:
        if(evt.isPopupTrigger())
        {
            PopUp(evt);
        }
    }//GEN-LAST:event_ArbolitoMousePressed

    private void ArbolitoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArbolitoMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger())
        {
            PopUp(evt);
        }
    }//GEN-LAST:event_ArbolitoMouseReleased

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        if(AlienSeleccionado instanceof Explorador)
        {
            Explorador E = (Explorador)AlienSeleccionado;
            EditarName.setText(E.getNombre());
            EditarEdad.setValue(E.getEdad());
            DefaultListModel m = (DefaultListModel) EditarLista.getModel();
            for (int i = 0; i < m.getSize(); i++) {
                m.addElement(E.getPlanetasExplorados().get(i));
            }
        }
    }//GEN-LAST:event_EditarActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Nombre: "+AlienSeleccionado.getNombre()+"\n"
                + "Edad: "+AlienSeleccionado.getEdad()+"\n"
                + "Amenaza: "+AlienSeleccionado.isAmenaza()+"\n"
                + "Raza: "+AlienSeleccionado.getRaza().getNombre()
        );
    }//GEN-LAST:event_ImprimirActionPerformed

    private void EditarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBotonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EditarBotonActionPerformed

    public void UpdateFramePlanetas()
    {
        int i = M.getPlanetas().size() - 1;
        //Lista de Planetas
        DefaultListModel L = (DefaultListModel) EListaPlanetas.getModel();
        L.addElement(M.getPlanetas().get(i));
        EListaPlanetas.setModel(L);
        CNListaPlanetas.setModel(L);
        EditarListaPlanetas.setModel(L);
        
        //Combo Box Planetas
        DefaultComboBoxModel R = (DefaultComboBoxModel) RazaBox.getModel();
        R.addElement(M.getPlanetas().get(i));
        RazaBox.setModel(R);
        ComboPlanetas.setModel(R);
    }
    
    public void UpdateFrameRazas()
    {
        int i = M.getRazas().size() - 1;
        DefaultComboBoxModel R = (DefaultComboBoxModel) ERaza.getModel();
        R.addElement(M.getRazas().get(i));
        ERaza.setModel(R);
        CRaza.setModel(R);
        CNRaza.setModel(R);
        ARaza.setModel(R);
        EditarRaza.setModel(R);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AAbducidos;
    private javax.swing.JCheckBox AAmenaza;
    private javax.swing.JSpinner AEdad;
    private javax.swing.JButton AGuardar;
    private javax.swing.JTextField ANombre;
    private javax.swing.JComboBox<String> ARaza;
    private javax.swing.JTree Arbolito;
    private javax.swing.JButton CAdd;
    private javax.swing.JCheckBox CAmenaza;
    private javax.swing.JSpinner CAtrapados;
    private javax.swing.JSpinner CEdad;
    private javax.swing.JButton CGuardar;
    private javax.swing.JCheckBox CNAmenaza;
    private javax.swing.JSpinner CNEdad;
    private javax.swing.JButton CNGuardar;
    private javax.swing.JList<String> CNListaPlanetas;
    private javax.swing.JTextField CNName;
    private javax.swing.JList<String> CNPlanetasC;
    private javax.swing.JComboBox<String> CNRaza;
    private javax.swing.JTextField CNombre;
    private javax.swing.JComboBox<String> CRaza;
    private javax.swing.JComboBox<String> ComboPlanetas;
    private javax.swing.JCheckBox EAmenaza;
    private javax.swing.JSpinner EEdad;
    private javax.swing.JButton EGuardar;
    private javax.swing.JList<String> ELista;
    private javax.swing.JList<String> EListaPlanetas;
    private javax.swing.JTextField EName;
    private javax.swing.JComboBox<String> EPlanetaF;
    private javax.swing.JComboBox<String> ERaza;
    private javax.swing.JMenuItem Editar;
    private javax.swing.JSpinner EditarAAtrapados;
    private javax.swing.JButton EditarAdd;
    private javax.swing.JCheckBox EditarAmenaza;
    private javax.swing.JButton EditarBoton;
    private javax.swing.JSpinner EditarEdad;
    private javax.swing.JSpinner EditarHAtrapados;
    private javax.swing.JList<String> EditarLista;
    private javax.swing.JList<String> EditarListaPlanetas;
    private javax.swing.JTextField EditarName;
    private javax.swing.JComboBox<String> EditarPF;
    private javax.swing.JComboBox<String> EditarRaza;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Imprimir;
    private javax.swing.JList<String> ListaAliens;
    private javax.swing.JCheckBox PAgua;
    private javax.swing.JTextField PName;
    private javax.swing.JPopupMenu POPUPMENU;
    private javax.swing.JSpinner PTamaño;
    private javax.swing.JSpinner PTemperatura;
    private javax.swing.JTextField RNombre;
    private javax.swing.JComboBox<String> RazaBox;
    private javax.swing.JButton RegistrarPlaneta;
    private javax.swing.JButton RegistrarRaza;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    private ManejadorDatos M = new ManejadorDatos();
    private Aliens AlienSeleccionado;
    private DefaultMutableTreeNode NodoSeleccionado;
    
    public void Defaults()
    {
        M.getPlanetas().add(new Planetas("Jupiter",100,100,false));
        UpdateFramePlanetas();
        M.getPlanetas().add(new Planetas("Marte",300,300,false));
        UpdateFramePlanetas();
        M.getRazas().add(new Raza(M.getPlanetas().get(0),"Joviano"));
        UpdateFrameRazas();
        M.getRazas().add(new Raza(M.getPlanetas().get(1),"Marciano"));
        UpdateFrameRazas();
        M.getAliens().add(new Cazador(100,"Alien Juan",23,true,M.getRazas().get(0)));
        M.getAliens().add(new Abduzcan(100,"Alien Carlos",23,true,M.getRazas().get(1)));
        M.getPlanetas().get(1).getAlien().add(M.getAliens().get(1));
        M.getPlanetas().get(0).getAlien().add(M.getAliens().get(0));
    }
}
